FLATTEN_MODELS = [
    "Transformer",
    "VanillaLSTM",
    "VanillaLSTMSeq2Seq",
    "VanillaLSTMSeq2SeqAttn",
]
QUANTILES_OPTIM_PARAMS = {
    "lr": 0.0001,
    "betas": [0.9, 0.999],
    "eps": 1e-9,
    "quantiles": [0.1, 0.5, 0.9],
    "warmup": False,
    "T_max_epoch": 100,
    "lr_min": 0.00001,
}
OPTIM_PARAMS = {
    "lr": 0.0001,
    "betas": [0.9, 0.999],
    "eps": 1e-9,
    "quantiles": [],
    "warmup": False,
    "T_max_epoch": 100,
    "lr_min": 0.00001,
}
MODEL_PARAMS = {
    "SpatiotemporalTransformerSeq2Seq": {
        "patch_size": 8,
        "d_model": 72,
        "num_heads": 9,
        "num_layers": 6,
        "use_cuda": True,
        "dropout": 0.2,
    },
    "Transformer": {
        "d_model": 72,
        "num_heads": 8,
        "N": 6,
        "use_cuda": True,
        "embed_mode": "Embedding",
        "dropout": 0.2,
    },
    "VanillaLSTM": {
        "linear_output_size": 72,
        "lstm_hidden_size": 72,
        "lstm_num_layers": 6,
        "hidden_seq_len": 10,
        "one_step_ahead": True,
        "use_cuda": True,
        "dropout": 0.2,
    },
    "VanillaLSTMSeq2Seq": {
        "linear_output_size": 72,
        "lstm_hidden_size": 72,
        "lstm_num_layers": 6,
        "one_step_ahead": True,
        "use_cuda": True,
        "dropout": 0.2,
        "sigmoid_output": False,
    },
    "VanillaLSTMSeq2SeqAttn": {
        "linear_output_size": 72,
        "lstm_hidden_size": 72,
        "lstm_num_layers": 6,
        "one_step_ahead": True,
        "use_cuda": True,
        "dropout": 0.2,
        "sigmoid_output": False,
    },
    "ConvLSTM": {
        "input_channels": 1,
        "hidden_channels": [8, 8, 8, 8, 8, 8],
        "kernel_size": 3,
        "pred_input_dim": 10,
        "one_step_ahead": True,
        "use_cuda": True,
        "dropout": 0.2,
        "sigmoid_output": False,
    },
    "ConvLSTMSeq2Seq": {
        "projection_channel": 8,
        "hidden_channels": [8, 8, 8, 8, 8],
        "kernel_size": 3,
        "one_step_ahead": True,
        "use_cuda": True,
        "dropout": 0.2,
        "sigmoid_output": False,
    },
    "ConvLSTMSeq2SeqAttn": {
        "projection_channel": 8,
        "hidden_channels": [8, 8, 8, 8, 8],
        "kernel_size": 3,
        "one_step_ahead": True,
        "use_cuda": True,
        "dropout": 0.2,
        "sigmoid_output": False,
    },
    "CNMM": {
        "input_channels": 1,
        "z_channels": 8,
        "emission_channels": 8,
        "transition_channels": 8,
        "rnn_channels": [8, 8, 8, 8, 8],
        "encoder_channels": 8,
        "kernel_size": 3,
        "pred_input_dim": 10,
        "encoder_layer": 2,
        "rnn_dropout_rate": 0.0,
        "use_cuda": True,
        "bottleneck": True,
        "use_sigmoid": False,
    },
    "DMM": {
        "input_channels": 1,
        "z_channels": 8,
        "emission_channels": [8, 4],
        "transition_channels": 72,
        "encoder_channels": [4, 8],
        "rnn_input_dim": 72,
        "rnn_channels": 72,
        "kernel_size": 3,
        "num_layers": 5,
        "rnn_dropout_rate": 0.0,
        "use_cuda": True,
    },
}
